### PR TITLE
OSX: Fixed bug that deleted ``clix-logo.svg`` in build

### LINKED ISSUE #27: Build deletes ``static/assets/clix-logo.svg``
The build script deletes ``static/assets/clix-logo.svg`` when it recursively removes the ``static`` directory and its content.  The build script uses ``static`` as a working directory for build artifacts so it makes sense that it would want to clean up, but there seems to be a baby in that bath water.

@cjshawMIT @resource11

### PR DESCRIPTION
**Pull request by pwilkins**
What was getting deleted in the build was all the contents of the ``/static``
directory.  I changed the build script so that only the build artifacts
are deleted from ``/static``.
I also updated the osx launcher to work better.

While I made these changes only in OSX, other platform build scripts should be compared and possibly updated.

Fixes #27 
@cjshawMIT @resource11

### CODE REVIEW

File: scripts/build_scripts/build_script_osx_ssl.sh [hunk 1]
```diff
@@ -57,10 +65,6 @@ cp scripts/launchers/unplatform_osx_ssl.sh bundle/
 mkdir bundle/modules
 cp -r modules/* bundle/modules/
 
-# copy over utility files for FSP data extraction
-cp scripts/data_extraction/DataExtractionScript.bat bundle/
```
Comment (cjshawMIT) [inline scripts/build_scripts/build_script_osx_ssl.sh]: Why did you remove these two lines?

Comment (pwilkins) [inline scripts/build_scripts/build_script_osx_ssl.sh]: Since they're ``.bat`` files and unable to run on OSX, I thought that they served no purpose.  I'm open to other opinions.  :-)

Comment (cjshawMIT) [inline scripts/build_scripts/build_script_osx_ssl.sh]: Ah, you're too logical 👍
